services:
  - type: web
    name: copyspark-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn aiwriter.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: aiwriter.settings
      - key: DATABASE_URL
        fromDatabase:
          name: copyspark-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: copyspark-db
    plan: free
