# Generated by Django 5.2.1 on 2025-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_trialsessionlog_delete_trialaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialsessionlog',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trialsessionlog',
            name='abuse_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trialsessionlog',
            name='trial_uses',
            field=models.IntegerField(default=0),
        ),
    ]
